# Generated by Django 5.2.7 on 2025-10-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_customer_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_order_number',
            field=models.IntegerField(default=0),
        ),
    ]
