# Generated by Django 5.2.7 on 2025-10-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_user_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_order_number',
            field=models.IntegerField(default=1),
        ),
    ]
