services:
  - type: web
    name: ecommerce-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ecommerce.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.settings
